#header配置
headers:
  User-Agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"
  Accept: "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7"
  Accept-Encoding: "gzip, deflate, br, zstd"
  Accept-Language: "zh-CN,zh;q=0.9,en;q=0.8"
  Connection: "keep-alive"
  Host: "www.masadora.jp"

#cookie配置
cookies:
  _language: "zh_CN"
  __td_signed: "true"
  _kfcq: "1"
  _ktbn: "1"
  _kibv: "1"
  _kgnm: "1"
  _kphj: "1"
  _kdhm: "1"
  _kgzm: "1"

  #以下改成你自己的
  __snaker__id: ""
  _dasm: ""
  Hm_lvt_247137ad66d12388fca4bebfa347e8f6: ""
  _gcl_au: ""
  _ga: ""
  _uetvid: ""
  _td: ""
  _ga_9L69NX8V77: ""
  JSESSIONID: ""
  gdxidpyhxdE: ""
  __afmk: ""

# 生成的excel文件路径
path: "./MasadoraOrder.xlsx"